[phases.setup]
nixPkgs = ["nodejs"]
cmds = ["corepack enable"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile=false"]

[phases.build]
cmds = ["pnpm --filter web build"]

[start]
cmd = "pnpm --filter web prisma migrate deploy && pnpm --filter web start --hostname 0.0.0.0 --port ${PORT:-3000}"
